order:
  service:
    message: welcome to order service
#custom properties
customer-eureka-url: ${protocal}customer-service
restaurent-eureka-url: ${protocal}restaurent-service
protocal: http://
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orders
